### PR TITLE
New alias strategy for MacOS

### PR DESCRIPTION
**Pull request by lleites**
Changed the python3 alias strategy used for it to work also on MacOS versions that already have python installed.

### CODE REVIEW

**Comment by lleites** [comment]
Please check on this run how the problem is solved, I was unable to test with the Arm64 self-hosted version.
https://github.com/lleites/pymgclient/actions/runs/3023585634

**Comment by antaljanosbenjamin** [comment]
First of all, thanks for contribution! Unfortunately it doesn't wprk for python 3.9. If you check the builds, all the python 3.9 builds are using python 3.10.

**Comment by lleites** [comment]
Sorry I am blind :) 
Now I think I got it right https://github.com/lleites/pymgclient/runs/8275444984?check_suite_focus=true

**Comment by antaljanosbenjamin** [comment]
Yes, this time you got it right, but this won't work on ARM machines, because the action doesn't support it. I tried to solve it in a few ways, but we had some issues with our Mac machine (it is hosted in the cloud an we had issues accessing it, so we had to open a ticket for them, etc). Next week I will have more time to check this and hopefully manage to figure out something that works an all mac machines. If not, then I will use your solution on x64 and do something else on ARM machines. That also requires some investigation (the differently compiled python versions, the available packages, not mentioning the "universal binaries" that are hard to work with in a C written python package that depends on some development libs...), but I will try to do my best next week.

**Comment by lleites** [comment]
Ok, I understand that there is some work to be done in the runners as described here https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#macos
The problem I see is that the current version of the library would break on most of the systems presently, as you can see on the scheduled CI of master. And the fix is blocked by an infra problem for M1 chipsets that is unrelated to the fix.
Can not you postpone the fix of the infra for later by disabling this M1 binaries, it can still be installed from source. In that case, it could be possible to release the fixed version. 
IMHO this would be an improvement over the current situation that is the package not been able to install on most systems.

**Comment by antaljanosbenjamin** [comment]
> The problem I see is that the current version of the library would break on most of the systems presently, as you can see on the scheduled CI of master.

Yes, this is unfortunately true.

> And the fix is blocked by an infra problem for M1 chipsets that is unrelated to the fix.

Yes, but I wouldn't like to release something that is:
 - not well understood what exactly is linked, etc. e.g.: there might be inconsistencies with the OpenSSL or other library versions. This means changing the way we release binaries also requires some resources to make sure we are releasing something that is really good.
 - change our CI to work in a totally different way that is not useful in the future, thus I would like to find a way that works also for M1.

We have an important deadline about some architectural work in Memgraph this week, after that (second half of the week) I can spend more time on this to fix this thing.

**Comment by antaljanosbenjamin** [comment]
I forgot to ask you about this:
> IMHO this would be an improvement over the current situation that is the package not been able to install on most systems.

Why do you think the package cannot be installed in most of the systems? Although the code is not correct (the import path is wrong), it works without any issues on Ubuntu 22.04 and 20.04 and on MacOS 11&12 without any issues. The problem became a blocking error with a recent version of setuptools or virtualenv.

**Comment by lleites** [comment]
Based on my experience, no one is locking the versions they use of virtualenv or setuptools, everyone uses latest from them. 
People locks versions after this initial setup.
Many tools like poetry install the latest versions, so if you use poetry, it will install the latest versions of these two packages, and you would have a broken setup on next CI run.

**Comment by antaljanosbenjamin** [comment]
Thanks for the explanation! I definitely wasn't aware of this as I am not using python extensively. I will bring this now and we will discuss whether we prioritize this over our deadline.

**Comment by antaljanosbenjamin** [comment]
After quick discussion I will try to fix this right now. I will keep you updated, hopefully this will be fixed soon.

**Comment by lleites** [comment]
Great, thanks! I will be monitoring the situation and I have a MacBook with M1 chipset, so please let me know if I can help anyhow

**Comment by antaljanosbenjamin** [comment]
The solution seems to be easier than I thought. Somehow the alias didn't work, but the solution is basically the same: using the major and minor version when calling python [seems to solve the problem](https://github.com/memgraph/pymgclient/runs/8305583190?check_suite_focus=true). I have a PR open where I need to update the release workflow, version and maybe the docs, but hopefully today there will be another version out there.

As far as I know you noticed the issue, can I ask you to try out the new package as soon as I will have a properly built version of it?

**Comment by lleites** [comment]
Yes, that would do the trick! I would be happy to test and give you feedback about this as soon as you have a release!
Will leave the PR open for communication purposes, or should we create a release "issue"?

**Comment by katarinasupe** [comment]
Hi @lleites, thank you so much for the contribution and feedback. If you still haven't, please [join our Discord server](https://discord.gg/memgraph), where it will be easier to communicate further. Looking forward to meeting you! 😄

**Comment by lleites** [comment]
Ok, closing this PR. I am on the Discord server, ping me there once you have a new release. Thanks!

**Pull request closed without merging**
