### PR TITLE
[E084-MG < T0542-MG] Support macos

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**

### CODE REVIEW

**Comment by antaljanosbenjamin** [comment]
The goal of this PR is to make sure binary packages can be built for Mac OS 10.15+ for Python 3.{7,8,9} on x64. It aim to make it work older version of MacOS or Python, or on the new arm64 architecture (M1 CPU).

Building all of the release binaries and updating the documentation is coming in a subsequent PR.

**Comment by antaljanosbenjamin** [comment]
https://test.pypi.org/project/pymgclient/0.2.dev2/#files

**Review by gitbuda — COMMENTED** [review]
Does it make sense to put the `null` problem description somewhere, if nothing else, then in the PR description?

**Comment by gitbuda** [comment]
> Does it make sense to put the `null` problem description somewhere, if nothing else, then in the PR description?

That's explained in the Python docs, so all good.

**Review by gitbuda — APPROVED** [review]

**Pull request merged**
